name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue appears to be staled. Please update status and need or risk for it to be archived.'
        stale-pr-message: 'This PR appears to be staled. Please update status communicate with owners and reviewers to make some progress.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
